### ISSUE TITLE
Google Play Books - невалидный epub

### ISSUE THREAD

**Issue by Bupyc** [progit/progit2-ru#107]
https://github.com/progit/progit2/issues/111
вот ветка обсуждения на английской версии. Проблема такая же.
Можете исправить? Я не знаю как сделать это своими силами.

**Comment by sadfuzzy** [comment]
Хорошо, изучу проблему

**Comment by Bupyc** [comment]
Если что, тот коммит что я отправил не полностью решает проблему. Это я по аналогии сделал с тем что сделали там.
Я не могу собрать книгу - одна из зависимостей не установилась из за бага в старой версии, а новая версия не совместима полностью видимо.
У меня при сборке книжки идут варнинги ещё что не сходятся какие то данные. У вас тоже? Я думаю проблема где то в структуре книжки.
Кстати как временное решение - конвертировал mobi в epub - работает. Но понятное дело что видимо часть функционала обрезалась.

**Comment by SergeiKuznetsov** [comment]
Проблема уже не актуальна? После подключения чекера никаких ошибок не наблюдается. 
Давайте закроем?

**Comment by Bupyc** [comment]
Да, похоже что с 2015 года проблема исправилась :)
