### ISSUE TITLE
[вопрос] Приветствуется ли перевод оставшихся разделов?

### ISSUE THREAD

**Issue by TheMozg** [progit/progit2-ru#157]
Или кто-то уже взял на себя эту задачу / перевод готов но не опубликован?

**Comment by alexey-lindberg** [comment]
Тоже интересует этот вопрос. Если нужна помощь с переводом, готов взять на себя какую-то часть.

**Comment by sadfuzzy** [comment]
Думаю, что можно переводить, я проверю и добавлю
