### ISSUE TITLE
[Вопрос] жив ли проект?

### ISSUE THREAD

**Issue by ssarkisy** [progit/progit2-ru#162]
Заметил, что последняя активность в проекте была довольно давно, поэтому возник вопрос, жив ли еще проект перевода?

Под жив понимаю, будут ли рассматриваться Pull Requst'ы в этот репозиторий.
Если да, то буду периодически слать PR's. 
На данный момент два моих ждет одобрения.

Спасибо.

**Comment by proninyaroslav** [comment]
Я бы организовал ответвление от данного проекта и развивал отдельно, ибо активности тут давно нет.

**Comment by eldarkg** [comment]
Лучше обратиться к администратору организации [progit](https://github.com/progit) и запросить у него права на добавление изменений с объяснением текущей ситуации проекта. Ответвляться стоит в самом последнем случаи.
П.С. тут и автосборка и публикация на официальном сайте. Ваш перевод не пропадет и будет полезен всем

**Comment by RomanKrasavtsev** [comment]
@ssarkisy удалось связаться с collaborator, пообещал посмотреть в ближайшее время.  @proninyaroslav так что не надо никаких форков :)

**Comment by ssarkisy** [comment]
@RomanKrasavtsev спасибо! Он как раз сегодня заревьювил все PR.
Возобновляю работу над переводом =)
