### ISSUE TITLE
Проблема с переводом в главе 7.1

### ISSUE THREAD

**Issue by NikitaLiashenko** [progit/progit2-ru#169]
В главе 7.1 слово "коммит" переведено как "фиксация", что вносит сумбур в понимание.
Так же встречается иногда в последующих главах

**Comment by ssarkisy** [comment]
Когда вносил правки в 6-ю главу, тоже заметил "фиксацию".
Хотелось бы узнать, какой вариант перевода предпочтительный.
"Коммит" или "Фиксация".

Лично я за "коммит".

**Comment by NikitaLiashenko** [comment]
Мне кажется "коммит" однозначно понятнее. К тому же в других главах используется именно эта формулировка

**Comment by DJm00n** [comment]
Глоссарий перевода консольного клиента git - https://www.transifex.com/djm00n/git-po-ru/glossary/ru/
Обсуждение глоссария - https://github.com/progit/progit2-ru/issues/36

---
commit (Noun) - коммит
commit (Verb) - закоммитить
Так сообщество решило: https://www.linux.org.ru/polls/polls/11129917/

**Comment by sadfuzzy** [comment]
Да, было дело
