### ISSUE TITLE
Жив ли проект?

### ISSUE THREAD

**Issue by vgip** [progit/progit2-ru#175]
Здравствуйте.

Хотел добавить свой вклад в перевод ProGit v2 на [git-scm.com/book/ru/v2](https://git-scm.com/book/ru/v2). Нашел раздел, который не переведен до конца: [Основы Git - Работа с удалёнными репозиториями](https://git-scm.com/book/ru/v2/%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D1%8B-Git-%D0%A0%D0%B0%D0%B1%D0%BE%D1%82%D0%B0-%D1%81-%D1%83%D0%B4%D0%B0%D0%BB%D1%91%D0%BD%D0%BD%D1%8B%D0%BC%D0%B8-%D1%80%D0%B5%D0%BF%D0%BE%D0%B7%D0%B8%D1%82%D0%BE%D1%80%D0%B8%D1%8F%D0%BC%D0%B8). Форкнул, захожу в проект и вижу, что материал уже давно переведен: [github.com/progit/progit2-ru/blob/master/book/02-git-basics/sections/remotes.asc](https://github.com/progit/progit2-ru/blob/master/book/02-git-basics/sections/remotes.asc). Непонятно только почему этот перевод отсутствует в полном объеме на git-scm.com/book/ru/v2/? Т.е. переведено все, до раздела: "Fetching and Pulling from Your Remotes". Жив ли проект?

**Comment by DJm00n** [comment]
Это вопрос к людям, которые занимаются  git-scm.com, сейчас зашел на https://git-scm.com/book/ru/v2 - вроде обновили уже.

**Comment by Cor-cor** [comment]
HTML-страницы на сайте обновили, а pdf и, видимо, остальные скачиваемые - не перезалили.
Сейчас на сайте ссылка на https://progit2.s3.amazonaws.com/ru/2016-02-16-2116f/progit-ru.1027.pdf, в котором "Fetching and Pulling from Your Remotes" ещё не переведён.

**Comment by a-kurau** [comment]
Что-то вообще ссылок для скачивания нет.
https://git-scm.com/book/ru/v2
https://i.imgur.com/hJJcnmj.png
