### ISSUE TITLE
Отсутсвует кириллический текст в pdf документе

### ISSUE THREAD

**Issue by shaihulud1992** [progit/progit2-ru#183]
Выполнил команды, предложенные в README:
$ bundle install
$ bundle exec rake book:build

C html документом все в порядке, а в pdf нет ни одного кириллического символа (даже кракозябр нет):
![image](https://user-images.githubusercontent.com/6010270/27013876-de32d6a0-4ef4-11e7-80f2-8951cce945b1.png)

**Comment by sadfuzzy** [comment]
Спасибо за репорт, посмотрю в течение недели

**Comment by dchesunas** [comment]
+1

**Comment by VokaMut** [comment]
+1

**Comment by sadfuzzy** [comment]
Извините, друзья, погряз в проектах, посмотрю в среду (23.08.17)

**Comment by foreverchaplin** [comment]
+1, эх, уже 30, а букв всё так и нет

**Comment by banzayats** [comment]
+1

**Comment by VokaMut** [comment]
и еще неделя прошла
Стоит ждать в этом месяце?

**Comment by dAN0n** [comment]
+1

**Comment by Karpovoleg74** [comment]
Хай

**Comment by RovingStone** [comment]
Можно закрыть, судя по всем. С новым Rakefile всё работает.
