### ISSUE TITLE
Вопрос по одному из заголовков

### ISSUE THREAD

**Issue by YYars** [progit/progit2-ru#188]
Доброго времени суток,

Корректно ли использовать заголовок «Перебазируй, пока перебазируешь (за такие названия нужно расстреливать)»?
В английской версии про расстрелы ничего нет. Кажется не очень удачной шуткой.

Всего хорошего

**Comment by sadfuzzy** [comment]
Измените?)

**Comment by sadfuzzy** [comment]
Спасибо, исправил: 
https://github.com/progit/progit2-ru/blob/master/book/03-git-branching/sections/rebasing.asc
