### ISSUE TITLE
automatic compilation and publishing of PDF and epub

### ISSUE THREAD

**Issue by jnavila** [progit/progit2-ru#190]
Hi all,

I'm in the process of making an automatic publication of the book on git-scm.com, using asciidoctor and Travis-CI for generating the PDF and epub.

This rework requires to move files around, change how cross-refs are done and change the build scripts. This is quite disruptive and would cause conflicts with ongoing changes.

Please ping me when the repo is idle, so that I can make the transition before you guys restart your work.

Thanks,

Jean-Noël

**Comment by jnavila** [comment]
@sadfuzzy Any problem? Any question?

**Comment by sadfuzzy** [comment]
@jnavila repo is idle, you just wanted me to ping you back :) I've accepted all the prs, so we are ready for update

**Comment by jnavila** [comment]
That's already been done! I merged the changes in #194. Have look [there](https://travis-ci.org/progit/progit2-ru). Every time someone pushes to master a build is triggered. If it's successful, the revision is tagged and the ebooks are [uploaded](https://github.com/progit/progit2-ru/releases). 

The compiled books are available at https://git-scm.com/book/ru .

**Comment by jnavila** [comment]
If it's ok for you, then the issue can be closed.
