### ISSUE TITLE
Глава 4.8 Git на сервере - GitLab - неоднозначное предложение 

### ISSUE THREAD

**Issue by dimio** [progit/progit2-ru#197]
> Там вы найдёте помощь по установке GitLab посредством рецептов Chef, на виртуальную машину Digital Ocean, или из RPM или DEB пакетов (которые на момент написания **всё** находились в бета-версии).

Не совсем ясно, имеется в виду, что пакеты **всё ещё** находились в бета-версии или что в ней находились **все** пакеты?

**Comment by sadfuzzy** [comment]
всё ещё
