### ISSUE TITLE
Потерявшиеся кавычки

### ISSUE THREAD

**Issue by Bargamut** [progit/progit2-ru#198]
Привет!

В файле по адресу:
`progit2-ru/book/09-git-and-other-scms/sections/import-hg.asc`

Блок текста про Mercurial, после слов:

> Если же все имена выглядят хорошо, этот файл и вовсе не потребуется. В нашем примере мы хотим чтобы данные выглядели так:

Стоит поставить кавычки в блоке кода:

> "bob"="Bob Jones <bob@company.com>"
> "bob@localhost"="Bob Jones <bob@company.com>"
> "bob jones <bob <AT> company <DOT> com>"="Bob Jones <bob@company.com>"
> "bob <bob@company.com>"="Bob Jones <bob@company.com>"

Нынешний вариант не соответствует формату, ожидаемому утилитой hg-fast-export.

**PS:** неплохо бы сделать примечание, чтобы обратили внимание на системные требования в описании [репозитория](https://github.com/frej/fast-export).
К примеру, с Mercurial ниже версии 4.6 в последних версиях утилиты от v180610 могут быть [проблемы при запуске](https://github.com/frej/fast-export/issues/132#issuecomment-399871721).

**Comment by Morganov** [comment]
Привет!
Лучше поздно, чем никогда. Поэтому отвечу.

Кавычки поправлены.

На счёт примечания: этот репозиторий - не собственная интерпретация книги, а перевод. Поэтому такие полезные уточнения следует направлять в англ. версию.

Так или иначе, спасибо за замечание. Я предложу уточнение в оригинал.

**Comment by SergeiKuznetsov** [comment]
@Morganov но в английской версии это поправлено 3 года назад. За полгода до того, как @Bargamut оставил это замечание тут. 

> Кавычки поправлены.

Правки пока не готовы к публикации? 
И почему **tag** переименовываем в теги? Устоявшийся перевод — **метка**. 
Аннотированная метка и упрощенная метка. Не стоит менять терминологию.
Словом **тег** мы называем много других вещей и возникнет путаница.

**Comment by Morganov** [comment]
> @Morganov но в английской версии это поправлено 3 года назад. За полгода до того, как @Bargamut оставил это замечание тут.
> 
> > Кавычки поправлены.
> 
> Правки пока не готовы к публикации?

Да, были конфликты слияния. Исправления доступны в #362

**Comment by Bargamut** [comment]
@Morganov Да, изменения влиты, однако по адресу всё ещё некорректный старый вариант:
[ссылка на страницу](https://git-scm.com/book/ru/v2/Git-%D0%B8-%D0%B4%D1%80%D1%83%D0%B3%D0%B8%D0%B5-%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D1%8B-%D0%BA%D0%BE%D0%BD%D1%82%D1%80%D0%BE%D0%BB%D1%8F-%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D0%B9-%D0%9C%D0%B8%D0%B3%D1%80%D0%B0%D1%86%D0%B8%D1%8F-%D0%BD%D0%B0-Git)

Можно ли как-то ещё повлиять на актуализацию?

**Comment by SergeiKuznetsov** [comment]
Инструкции говорят: please ping @jnavila to get started with epub publication ))

**Comment by SergeiKuznetsov** [comment]
Обновление на сайте прошло, можно закрыть.
