### ISSUE TITLE
Fonts in the PDF

### ISSUE THREAD

**Issue by Bakuutin** [progit/progit2-ru#21]
Cyrillic is displayed incorrectly. Firstly the main Cyrillic text has a thicker typeface than the Latin, and secondly (and most importantly) headers and a "Table of Contents" aren't displayed.
Here's how it looks:
![](http://habrastorage.org/files/88f/018/dcb/88f018dcb4fd41c7a82d62527591a801.png)
![](http://habrastorage.org/files/b8f/cd0/5b3/b8fcd05b3b7147dcbcb54cb7cb0a9f40.png)

**Comment by evgkrsk** [comment]
Unable to reproduce :-) (PDF from [here](https://progit2.s3.amazonaws.com/ru/2014-12-28-55e59/progit-ru.255.pdf))

Perhaps something wrong with your PDF building toolchain?

![toc](https://cloud.githubusercontent.com/assets/79869/5606471/6de89a84-945b-11e4-9907-4e0c54c93b13.png)
![thickness](https://cloud.githubusercontent.com/assets/79869/5606496/f536c272-945b-11e4-8ef0-a2584c9ae51f.png)

**Comment by sadfuzzy** [comment]
@Bakuutin, how is it going?
