### ISSUE TITLE
Неправильный перевод в главе 3.5

### ISSUE THREAD

**Issue by gellerda** [progit/progit2-ru#241]
В оригинале в главе 3.5/ в подразделе "Отслеживание веток" / в первом предложении:

> (and the branch it tracks is called an “upstream branch”)

переведен неправильно с изменением смысла:
 
> (или иногда “upstream branch”).

Правильный перевод:

> (а удаленную ветку, за которой ведется слежение, называют “upstream branch”).

P.S.
Кроме того, термин “tracking branch” было бы логичнее перевести, как "ветка слежения" или "следящая ветка".

**Comment by Morganov** [comment]
Спасибо! Исправлено.
