### ISSUE TITLE
Разнообразные опечатки

### ISSUE THREAD

**Issue by StanleySane** [progit/progit2-ru#264]
Ниже перечислены опечатки, которые наиболее бросились в глаза (продолжение #253)

В файле [book/05-distributed-git/sections/contributing.asc](https://github.com/progit/progit2-ru/blob/master/book/05-distributed-git/sections/contributing.asc)

- строка 613. Вместо `Возможо` должно быть `Возможно`.
- строка 614. Вместо `разрашаете` должно быть `разрешаете`.

В файле [book/05-distributed-git/sections/maintaining.asc](https://github.com/progit/progit2-ru/blob/master/book/05-distributed-git/sections/maintaining.asc)

- строка 123. Вместо `безаконфликтно` должно быть `бесконфликтно`.
- строка 325. Вместо `тематческая` должно быть `тематическая`.
- строка 380. Вместо `выхотите` должно быть `вы хотите` (пробел). Ошибка встречается дважды в строке.
- строка 407. Вместо `догоживущие` должно быть `долгоживущие`.
- строка 465: Вместо `публчниый` должно быть `публичный`.
- строка 473: Вместо `ипортировать ваш публиный ключ` должно быть `импортировать ваш публичный ключ`.

В файле [book/06-github/sections/2-contributing.asc](https://github.com/progit/progit2-ru/blob/master/book/06-github/sections/2-contributing.asc)

- строка 19. Вместо `участие в обсуждения` должно быть `участие в обсуждениях`.
- строка 176. Вместо `на котрой` должно быть `на которой`.
- строка 212. Вместо `вернетесь к к этому запросу` должно быть `вернетесь к этому запросу` (лишняя буква `к`).
- строка 285. Вместо `перебазровать` должно быть `перебазировать`.
- строка 298. Вместо `находятя` должно быть `находятся`.

В файле [book/06-github/sections/3-maintaining.asc](https://github.com/progit/progit2-ru/blob/master/book/06-github/sections/3-maintaining.asc)

- строка 41. Вместо `добаить` должно быть `добавить`.
- строка 88. Вместо `ко всем зупросу` должно быть `ко всему запросу`.

В файле [book/07-git-tools/sections/rewriting-history.asc](https://github.com/progit/progit2-ru/blob/master/book/07-git-tools/sections/rewriting-history.asc)

- строка 94. Вместо `самая старый` должно быть `самый старый`.

В файле [book/07-git-tools/sections/advanced-merging.asc](https://github.com/progit/progit2-ru/blob/master/book/07-git-tools/sections/advanced-merging.asc)

- строка 486. Вместо `сделать ее` должно быть `сделать его`.

В файле [book/07-git-tools/sections/submodules.asc](https://github.com/progit/progit2-ru/blob/master/book/07-git-tools/sections/submodules.asc)

- строка 359. Вместо `в одно и тоже время` должно быть `в одно и то же время` (пробел между то и же).

В файле [book/08-customizing-git/sections/attributes.asc](https://github.com/progit/progit2-ru/blob/master/book/08-customizing-git/sections/attributes.asc)

- строка 4. Вместо `Git применят их` должно быть `Git применяет их`.
- строка 13. Вместо `вам пригодииться` должно быть `вам пригодиться`.
- строка 13. Вместо `файлов, которы следует` должно быть `файлов, которые следует`.

В файле [book/08-customizing-git/sections/hooks.asc](https://github.com/progit/progit2-ru/blob/master/book/08-customizing-git/sections/hooks.asc)

- строка 44. Вместо `сообщние` должно быть `сообщение`.

**Comment by Morganov** [comment]
Спасибо! Исправления в #265
