### ISSUE TITLE
Книга в формате HTML

### ISSUE THREAD

**Issue by Starina123** [progit/progit2-ru#281]
Есть ли возможность в релиз добавить сборку книги в формате HTML для скачивания?

**Comment by Morganov** [comment]
Релизом книги занимается отдельный проект: https://github.com/progit/progit2-pub
Можно написать запрос туда или дождаться пока у меня будет время это сделать.

**Comment by Starina123** [comment]
Спасибо, я подожду

**Comment by Morganov** [comment]
Всё оказалось гораздо проще.
progit.html теперь включается в релиз https://github.com/progit/progit2-ru/releases/tag/2.1.52
