### ISSUE TITLE
Битая ссылка на изображение

### ISSUE THREAD

**Issue by Pooort** [progit/progit2-ru#309]
На [странице](https://git-scm.com/book/ru/v2/Appendix-A%3A-Git-%D0%B2-%D0%B4%D1%80%D1%83%D0%B3%D0%B8%D1%85-%D0%BE%D0%BA%D1%80%D1%83%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F%D1%85-Git-%D0%B2-IntelliJ-%2F-PyCharm-%2F-WebStorm-%2F-PhpStorm-%2F-RubyMine)  нет ссылки на изображение `Окно версионного контроля в средах JetBrains.`

**Comment by Morganov** [comment]
Всё верно, как и на [странице оригинала](https://git-scm.com/book/en/v2/Appendix-A%3A-Git-in-Other-Environments-Git-in-IntelliJ-%2F-PyCharm-%2F-WebStorm-%2F-PhpStorm-%2F-RubyMine).

Проблема не в книге и не в картине, а в процессе публикации её на сайте git-scm.com, за который отвечает репозиторий https://github.com/git/git-scm.com
Вы можете сообщить об ошибке там.
