### ISSUE TITLE
Ошибка в статье 3.6 Ветвление в Git - Перебазирование

### ISSUE THREAD

**Issue by readandwrite864** [progit/progit2-ru#329]
В середине статьи написано: 
```bash
$ git rebase master server
```
> Эта команда добавит изменения ветки server в ветку master, как это показано на... (Рисунок 42)

![image](https://user-images.githubusercontent.com/63188034/99839490-1d407700-2bae-11eb-930e-7b9cfe8c4113.png)

Разве не должно быть наоборот (команда добавит изменения ветки master в ветку server)?

**Comment by SergeiKuznetsov** [comment]
Истина где-то рядом.
В ветку мастер действительно ничего не добавляется, так как она не изменяется.
А изменяется ветка сервер, которая заново пересобирается поверх актуального состояния ветки мастер. 
Изменения ветки мастер конечно попадут в ветку сервер, но они окажутся в начале цепочки коммитов.
Rebase означает: взять все изменения, которые были зафиксированы в одной ветке, и повторно применить их на базе другой ветки.

Читаем оригинал:
> This replays your `server` work on top of your `master` work, as shown in <название рисунка>
(Не знаю зачем в оригинале тут пытаются запихнуть во фразу название самого рисунка. Выглядит коряво.)

Дословно:
**Это повторит вашу работу в ветке `server` поверх ветки `master`, как показано на рисунке:**

Рисунок в наших терминах корректнее назвать так:
**Перебазирование ветки `server` поверх ветки `master`**
Хотя может быть уместно говорить перемещение или пересборка. 
Вижу что в книге используется термин **перебазирование**.
В официальной локализации Git сейчас говорят **перемещение**

**Comment by SergeiKuznetsov** [comment]
В Microsoft переводят слово **rebase** длинной строкой: **переместить изменения из одной ветви в другую**

**Comment by SergeiKuznetsov** [comment]
#350 добавил правку
