### ISSUE TITLE
Определиться с использованием слова т[еэ]г

### ISSUE THREAD

**Issue by nikolai-shabalin** [progit/progit2-ru#333]
В книге написание слова тег разное, то "т**э**г", то "т**е**г".

Нужно определиться с написанием и придерживаться одного.

Предложу через "е", так как в Веб-стандартах уже обсуждали - https://github.com/web-standards-ru/dictionary/blob/master/dictionary.md#tag

**Comment by Morganov** [comment]
Добавлено в заметки #340

**Comment by Morganov** [comment]
Исправлено в #341
