### ISSUE TITLE
В русских текстах принято использовать «кавычки-ёлочки»

### ISSUE THREAD

**Issue by SergeiKuznetsov** [progit/progit2-ru#336]
Очень режут глаз используемые по всему тексту “английские двойные кавычки”.
Давайте поправим?

**Comment by Morganov** [comment]
Исправляется в #337

**Comment by SergeiKuznetsov** [comment]
@Morganov Ещё считаю что вот тут лишние кавычки для обрамления Alt-теста
`image::images/centralized_workflow.png["Централизованный рабочий процесс"]` 
С какой целью они там добавлены?
Ведь при сборке в HTML автоматически вставятся двойные кавычки вокруг теста в тегах. 
` alt="Централизованный рабочий процесс">`

**Comment by Morganov** [comment]
> 
> 
> @Morganov Ещё считаю что вот тут лишние кавычки для обрамления Alt-теста
> `image::images/centralized_workflow.png["Централизованный рабочий процесс"]`
> С какой целью они там добавлены?
> Ведь при сборке в HTML автоматически вставятся двойные кавычки вокруг теста в тегах.
> ` alt="Централизованный рабочий процесс">`

Согласно документации asciidoc в квадратных скобках указываются параметры изображения: его название и размеры. Праметры разделяются запятыми. В русской версии используеются названия с запятыми, часть названия интерпретируется как параметр и приводит к пропаданию картинок. Поэтому было принято решение использовать кавычки для всех изображений.
Alt-текст, как и подпись рисунка формируются из строки перед `image::`
