### ISSUE TITLE
Directory → Каталог

### ISSUE THREAD

**Issue by SergeiKuznetsov** [progit/progit2-ru#352]
### Directory → Каталог

В соседней ветке https://github.com/progit/progit2-ru/issues/36 было обсуждение, но решение так и не приняли.
Вставлю дополнительные аргументы:

Слово **директория** — это вульгарная калька с английского слова **directory**, которое в русскоязычной документации (и литературе) в отношении хранения данных на блочных устройствах однозначно переводится как каталог более 30 лет, что отражено в куче всяких словарей и справочников.

В официальной локализации Git сейчас тоже используется **каталог**.
https://www.transifex.com/djm00n/git-po-ru/translate/#ru/git/21735619?q=text%3Adirectory

Сейчас в книге **292** раза написано директория, **107** раз каталог и даже **6** раз папка.

Предлагаю проверить все упоминания и привести к общему стилю.

**Comment by Morganov** [comment]
Поддерживаю!
Только ссылка указывает на другой проект, в котором вы тоже участвуете. Постарайтесь ссылаться на какие-то более объективные источники.

**Comment by Morganov** [comment]
Добавил некоторые уточнения в правила перевода #358

**Comment by Morganov** [comment]
Исправлено в #359 
"Папка" исправлено на "каталог" в #381, за исключением упоминаний, относящихся к почтовому клиенту.
