### ISSUE TITLE
Лишнее склеивание двойного минуса

### ISSUE THREAD

**Issue by leerg** [progit/progit2-ru#369]
В главе "Операции отмены" после текста: "Важно понимать, что git checkout..." два минуса слиты в тире.
![image](https://user-images.githubusercontent.com/7223702/106925118-d5e37480-6720-11eb-92ac-2cb376325f64.jpeg)

**Comment by leerg** [comment]
Ошибка на всех языках. Проверил в epub, pdf. Вероятнее всего и в html она есть

**Comment by SergeiKuznetsov** [comment]
Спасибо
![image](https://user-images.githubusercontent.com/13728212/106970045-85423a80-6765-11eb-803a-2e58e72d02c6.png)

Исправлено в #370

**Comment by leerg** [comment]
Создал, на основе исправления, pull request в английской версии: [https://github.com/progit/progit2/pull/1601](https://github.com/progit/progit2/pull/1601)
