### ISSUE TITLE
Отсутствует оглавление в html версии

### ISSUE THREAD

**Issue by leerg** [progit/progit2-ru#388]
В актуальной релизной версии [2.1.80](https://github.com/progit/progit2-ru/releases/tag/2.1.80) отсутствует оглавление в версии для html.
Если смотреть релизы около года назад то оглавление было. В английской версии тоже есть.

**Comment by SergeiKuznetsov** [comment]
Если собирать руками, то всё на месте.
А гитхабовский скрипт, собирающий релиз сломан для нас, пока не будет одобрен https://github.com/progit/progit2-pub/pull/9
@jnavila we need help!

**Comment by leerg** [comment]
Одобрено 🙂

**Comment by leerg** [comment]
В новой версии оглавление заработало 🙂
