### ISSUE TITLE
Ошибка в переводе в Главе 6

### ISSUE THREAD

**Issue by mshalmanov** [progit/progit2-ru#431]
Добрый день.

Ошибка перевода текста "Вместо этого, отправьте перебазированную ветку в новую на GiHub и откройте новый запрос на слияние, который указывает на предыдущий, затем закройте исходный." в [progit2-ru/book/06-github/sections/2-contributing.asc](https://github.com/progit/progit2-ru/blob/master/book/06-github/sections/2-contributing.asc)

**Comment by Morganov** [comment]
Исправлено в #452
