### ISSUE TITLE
Не выделены флаги в 7.5 Поиск

### ISSUE THREAD

**Issue by Viktor-Yegay** [progit/progit2-ru#448]
-c
--show-function
--break
--heading

**Comment by SergeiKuznetsov** [comment]
Что вы имеете в виду под «выделить»?

**Comment by Viktor-Yegay** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/73840279/183472296-3a693df8-6f13-4420-8ba1-d60a8f6d19c7.png)
Поменять цвет
